<!-- ONCBP Report Template -->
<div class="report-container">
    <div class="report-header">
        <div class="logo-container">
            <img src="{{ asset('images/OSCA.png') }}" alt="Logo" class="report-logo">
        </div>
        <div class="header-text">
            <h1>ONCBP Applicants</h1>
            <h3>Report Date: {{ $date }}</h3>
        </div>
    </div>

    <div class="report-summary">
        <p><strong>Total ONCBP Applicants:</strong> {{ $total }}</p>
    </div>

    <div class="report-table-container">
        <table class="report-table">
            <thead>
                <tr>
                    <th>No.</th>
                    <th>OSCA ID</th>
                    <th>Full Name</th>
                    <th>Age</th>
                    <th>Gender</th>
                    <th>Barangay</th>
                    <th>Milestone Age</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @forelse($applications as $index => $application)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>{{ $application->senior ? $application->senior->osca_id : 'N/A' }}</td>
                        <td>
                            @if($application->senior)
                                {{ $application->senior->first_name }} {{ $application->senior->middle_name ? substr($application->senior->middle_name, 0, 1) . '.' : '' }} {{ $application->senior->last_name }}
                            @else
                                N/A
                            @endif
                        </td>
                        <td>{{ $application->senior ? \Carbon\Carbon::parse($application->senior->date_of_birth)->age : 'N/A' }}</td>
                        <td>{{ $application->senior ? $application->senior->sex : 'N/A' }}</td>
                        <td>{{ $application->senior ? $application->senior->barangay : 'N/A' }}</td>
                        <td>{{ $application->benefitsApplication && $application->benefitsApplication->milestone_age ? $application->benefitsApplication->milestone_age : 'N/A' }}</td>
                        <td>{{ ucfirst($application->status) }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="8" style="text-align: center;">No ONCBP applications found</td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="report-footer">
        <p>Generated by ELDERA IMS on {{ $date }}</p>
    </div>
</div>